import Nott1 from '../images/The Warrior of Shattered Tears by Luna Smith.jpg';
import Nott2 from '../images/Awakening from the Sleep of Fear by Luna Smith.jpg';
import Nott3 from '../images/The Battle of Endless Seas by Luna Smith.jpg';
import Nott4 from '../images/The Soothing Wind of Longing by Luna Smith.jpg';
import Nott5 from '../images/Dreams of a Future Self by Luna Smith.jpg';

const content = [
    {
        id: 1,
        title: "Nott",
        alt: "Nott art collection - an oil painitng from Nott collection by Luna Smith",
        description: [],
        src: Nott1,
    },
    {
        id: 2,
        title: "",
        alt: "",
        description: ["We live in the endless loop of wonders."],
        src: "",
    },
    {
        id: 3,
        title: "The Warrior of Shattered Tears",
        alt: "The Warrior of Shattered Tears - an oil painitng from Nott collection by Luna Smith",
        description:  [],
        src: Nott1,
    },
    {
        id: 4,
        title: "",
        alt: "",
        description:  ["Blue tears dry up and form bricks", 
                       "Mothers create, relinquish survival tricks", 
                       "Pain, death, fear, starvation expose us", 
                       "Waves of bravery, sparks of hope enclose us", 
                       "There are bombs, dust and crushing loot",
                       "Mortals are crying for love and food",
                       "Souls are screaming to curses condemn",
                       "It is time to end the torment in our realm",
                       "There is no time for toys, laughter and rest", 
                       "It is a time of change the terror nest",
                        "There is no time for harmony and ingenuity", 
                        "It is time to start a new enhanced reality"],
        src: "",
    },
    {
        id: 5,
        title: "The Battle of Endless Seas",
        alt: "The Battle of Endless Seas - an oil painitng from Nott collection by Luna Smith",
        description: [],
        src: Nott3,
    },
    {
        id: 6,
        title: "",
        alt: "",
        description: ["We are moving forward",
                       "Time passes by",
                       "Faster and faster each time",
                       "We are standing still", 
                       "Empty space around us",
                       "Endless peace in our minds", 
                       "We are moving sideways", 
                       "Playing with the speed",
                       "Making our dreams real",
                       "We can never move back",
                       "We can only start over",
                       "From the moment we choose"],
        src: "",
    },
    {
        id: 7,
        title: "The Soothing Wind of Longing",
        alt: "The Soothing Wind of Longing - an oil painitng from Nott collection by Luna Smith",
        description: [],
        src: Nott4,
    },
    {
        id: 8,
        title: "",
        alt: "",
        description: ["Our greatest strength is peace",
                      "when we are safe, equal and free",
                      "Our most vehement struggle is war",
                      "when we live in fear and try to survive",
                      "Our most potent success is unity",
                      "when we evaluate, plan and evolve"],
        src: "",
    },
    {
        id: 9,
        title: "Awakening from the Sleep of Fear",
        alt: "Awakening from the Sleep of Fear- an oil painitng from Nott collection by Luna Smith",
        description: [],
        src: Nott2,
    },
    {
        id: 10,
        title: "",
        alt: "",
        description: ["A candle in the dark",
                      "Spark by spark",
                      "Lighting the corner of infinite space",
                      "There are invariably unreachable horizons",
                      "There are endless leaves to fall",
                      "Life brings fresh knowledge",
                      "An era carries a unique climate",
                      "A century begins with novel customs",
                      "A day delivers new reality"],
        src: "",
    },
    {
        id: 11,
        title: "Dreams of a Future Self",
        alt: "Dreams of a Future Self - an oil painitng from Nott collection by Luna Smith",
        description: [],
        src: Nott5,
    },
    {
        id: 12,
        title: "",
        alt: "",
        description: ["Trillions of tiny pieces enchanted in the past",
                      "Minds filled with consciousness sensations",
                      "To see, to touch, to eat, to breathe",
                      "The outer manifestation of the life force",
                      "All connected and constantly changing fate",
                      "To feel, to judge, to create, to destroy",
                      "Spirits like us - our astral doubles",
                      "Eternally strive to withstand, to never give up"],
        src: "",
    }
]

export default content