import Nott1 from '../images/The Warrior of Shattered Tears by Luna Smith.jpg';
import Nott2 from '../images/Awakening from the Sleep of Fear by Luna Smith.jpg';
import Nott3 from '../images/The Battle of Endless Seas by Luna Smith.jpg';
import Nott4 from '../images/The Soothing Wind of Longing by Luna Smith.jpg';
import Nott5 from '../images/Dreams of a Future Self by Luna Smith.jpg';

import Nott6 from '../images/The Blood of the Silent Unicorn by Luna Smith.jpg';
import Nott7 from '../images/Breathe of the Invisible Beast by Luna Smith.jpg';
import Nott8 from '../images/The Flame of the Eternal Triangle by Luna Smith.jpg';
import Nott9 from '../images/The Scale of the Blue Dragon by Luna Smith.jpg';
import Nott10 from '../images/The Heartbeat of the Raging Cyclone by Luna Smith.jpg';

const content = [
    {
        id: 1,
        title: "",
        alt: "Nott art collection - an oil painitng from Nott collection by Luna Smith",
        description: [],
        src: Nott1,
    },
    {
        id: 2,
        title: "",
        alt: "",
        description: ["We live in the endless loop of wonders."],
        src: "",
    },
    {
        id: 3,
        title: "The Warrior of Shattered Tears",
        alt: "The Warrior of Shattered Tears - an oil painitng from Nott collection by Luna Smith",
        description:  [],
        src: Nott1,
    },
    {
        id: 4,
        title: "",
        alt: "",
        description:  ["The Warrior of Shattered Tears,", 
                       "With a heart full of sorrow and pain", 
                       "Fought through battles, never in vain,", 
                       "Blue tears fall like rain.", 
                       "With each droplet that hit the ground,",
                       "A brick of life did rise,",
                       "Forging a path that was unbound,",
                       "With a strength that would surprise.",
                       "Through the fire and through the ice,", 
                       "The Warrior pressed on,",
                       "With a determination so precise,", 
                       "Victory would not be gone.",
                       "For every tear that fell,",
                       "A brick of hope was laid,",
                       "Till the path ahead was clear,",
                       "And the future was unafraid.",
                       "And though the tears may dry,",
                       "The Warrior's strength will stay,",
                       "For the bricks of life will never die,",
                       "And pave the way to a brighter day."],
        src: "",
    },
    {
        id: 5,
        title: "The Battle of Endless Seas",
        alt: "The Battle of Endless Seas - an oil painitng from Nott collection by Luna Smith",
        description: [],
        src: Nott3,
    },
    {
        id: 6,
        title: "",
        alt: "",
        description: ["The Battle of Endless Seas,",
                       "A fight against the tide,",
                       "With each wave, a new challenge,",
                       "And time moves on beside.", 
                       "We set sail on winds of change,",
                       "Through the storms and through the calm,", 
                       "Forging ahead, we will not derange,", 
                       "For the future is our qualm,",
                       "With each passing day,",
                       "We move forward with time,",
                       "Gaining strength in every way,",
                       "And leaving the past behind.",
                       "So let us raise our sails,",
                       "And face the winds with grace,",
                       "For the future awaits,",
                       "In the Endless Seas of Time and space."],
        src: "",
    },
    {
        id: 7,
        title: "The Soothing Wind of Longing",
        alt: "The Soothing Wind of Longing - an oil painitng from Nott collection by Luna Smith",
        description: [],
        src: Nott4,
    },
    {
        id: 8,
        title: "",
        alt: "",
        description: ["The Soothing Wind of Longing,",
                      "Blows through the stars above,",
                      "A gentle breeze, softly flowing,",
                      "Carries our souls to love.",
                      "For so long, we've been searching,",
                      "For a way to find peace, to be one,",
                      "With the universe that surrounds,",
                      "And the secrets that it's begun.",
                      "Like a symphony, the wind sings,",
                      "Of a world that's free from pain,",
                      "And with each note, our souls take wing,",
                      "And our longing is no longer in vain.",
                      "So let us open our hearts,",
                      "And listen to the wind song,",
                      "For the Soothing Wind of Longing,",
                      "Brings us to where we belong.",],
        src: "",
    },
    {
        id: 9,
        title: "Awakening from the Sleep of Fear",
        alt: "Awakening from the Sleep of Fear- an oil painitng from Nott collection by Luna Smith",
        description: [],
        src: Nott2,
    },
    {
        id: 10,
        title: "",
        alt: "",
        description: ["Awakening from the Sleep of Fear,",
                      "Like a candle in the dark,",
                      "Shining bright, shedding light,",
                      "On the shadows that once harked.",
                      "For so long, we lay in slumber,",
                      "Trapped by fear and doubt,",
                      "But now, we rise like thunder,",
                      "And cast the shadows out.",
                      "With each breath, we take control,",
                      "Like a beacon in the night,",
                      "The power to change and mold,",
                      "With each step, a new world is in sight."
                    ],
        src: "",
    },
    {
        id: 11,
        title: "Dreams of a Future Self",
        alt: "Dreams of a Future Self - an oil painitng from Nott collection by Luna Smith",
        description: [],
        src: Nott5,
    },
    {
        id: 12,
        title: "",
        alt: "",
        description: ["Dreams of a Future Self,",
                      "A vision of what's to be,",
                      "Trillions of tiny pieces,",
                      "Enchanted in the past, set free.",
                      "With eyes focused on the horizon,",
                      "We set our hearts alight,",
                      "For the future is our dominion,",
                      "And we'll chase it with all our might.",
                      "We'll take the pieces of our past,",
                      "And weave them into something new,",
                      "For the dreams of our future selves,",
                      "Will be the dreams that we pursue.",
                      "So let us dream of who we'll be,",
                      "And let our hearts take flight,",
                      "For the future is ours to see,",
                      "And it's a future that is bright."],
        src: "",
    },
    {
        id: 13,
        title: "The Blood of the Silent Unicorn",
        alt: "The Blood of the Silent Unicorn - an oil painitng from Nott collection by Luna Smith",
        description: [],
        src: Nott6,
    },
    {
        id: 14,
        title: "",
        alt: "",
        description: ["The Blood of the Silent Unicorn,",
                      "a mystery of ancient lore,",
                      "a symbol of purity and grace,",
                      "that we should never ignore.",
                      "Pure-blooded creature shining bright,",
                      "and flows through the veins of the past,",
                      "With a horn that glows like a sword,",
                      "runs wild, through the Universe, old.",
                      "But it's the blood that's the treasure,",
                      "that we all seek to find,",
                      "for it holds the power of healing,",
                      "and the magic of the mind.",
                      "As a reminder of the battle, forever known,",
                      "the blood that flowed, turned to stone.",
                      "Let it guide us through the night,",
                      "the source of all that's right."],
        src: "",
    },
    {
        id: 15,
        title: "Breathe of the Invisible Beast",
        alt: "Breathe of the Invisible Beast - an oil painitng from Nott collection by Luna Smith",
        description: [],
        src: Nott7,
    },
    {
        id: 16,
        title: "",
        alt: "",
        description: ["Breathe of the Invisible Beast,",
                      "mysterious, powerful, and wild,",
                      "which comes and goes discrete,",
                      "creating start dust and smiles of a child.",
                      "It moves through the hearts,",
                      "whispers through mighty arts,",
                      "a symphony of life and death,",
                      "a pure melody in your breath.",
                      "It cuddles, swirls, and passes by,",
                      "Gives life the strength to grow,",
                      "it shapes the land and sky,",
                      "a force that's always on the go.",
                      "A never-ending feast,",
                      "we can't see it with our eyes,",
                      "it's a breath of the invisible beast,",
                      "that keeps our world alive.",
                   ],
        src: "",
    },
    {
        id: 17,
        title: "The Flame of the Eternal Triangle",
        alt: "The Flame of the Eternal Triangle - an oil painitng from Nott collection by Luna Smith",
        description: [],
        src: Nott8,
    },
    {
        id: 18,
        title: "",
        alt: "",
        description: ["The Flame of the Eternal Triangle,",
                      "burns bright and never dies.",
                      "The catcher of the world right angle,",
                      "that reaches up to the skies.",
                      "The fire that's fueled by love urge,",
                      "and the bond that holds us tight,",
                      "flames that shimmer and merge,",
                      "in the dark and in the light.",
                      "The future, the present, and the past",
                      "create endless sides of eternal life.",
                      "It's a thing of beauty and strength,",
                      "that's been here since the world unfurled."],
        src: "",
    },
    {
        id: 19,
        title: "The Heartbeat of the Raging Cyclone",
        alt: "The Heartbeat of the Raging Cyclone - an oil painitng from Nott collection by Luna Smith",
        description: [],
        src: Nott9,
    },
    {
        id: 20,
        title: "",
        alt: "",
        description: ["The Heartbeat of the Raging Cyclone,",
                      "travels through the unknown,",
                      "a cosmic dance in the dark,",
                      "planets and galaxies hidden ark.",
                      "A storm of dust, energy, and souls,",
                      "a symphony of motion in black holes.",
                      "A lonely heartbeat in the void,",
                      "of the living things it employs.",
                      "Let bond with the cyclone heartbeat",
                      "a tempestuous rhythm, wild and vast,",
                      "the remainder of the universe's loveseat,",
                      "the power of the cosmic future and past."],
        src: "",
    },
    {
        id: 21,
        title: "The Scale of the Blue Dragon",
        alt: "The Scale of the Blue Dragon - an oil painitng from Nott collection by Luna Smith",
        description: [],
        src: Nott10,
    },
    {
        id: 22,
        title: "",
        alt: "",
        description: ["The Scale of the Blue Dragon,",
                      "the universe's hidden gem,",
                      "a planet, small and fragile,",
                      "that's part of a larger realm.",
                      "It spins and orbits, ",
                      "in the endless blue,",
                      "a dance of gravity and time, ",
                      "that's always new.",
                      "The blue dragon holds in its grasp,",
                      "a speck of dust among the stars,",
                      "that's a part of the cosmic clasp,",
                      "a treasure of the universe holding life."],
        src: "",
    },
    

]

export default content